version: '3.9'
services:

  db:
    container_name: vvpi_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:14-alpine
    networks:
      - network
    ports:
      - ${HOST_DB_PORT}:${DB_PORT}
    volumes:
      - vvpi_db_data:/var/lib/postgresql/data

  migration:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vvpi_migration
    entrypoint: ["make", "migrate-up"]
    depends_on:
      - db
    env_file:
      - ${ENV_FILE}
    networks:
      - network

  redis:
    container_name: vvpi_redis
    image: redis:7-alpine
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - network
    ports:
      - ${HOST_REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: vvpi_backend
    entrypoint: ["make", "run"]
    depends_on:
      - db
      - migration
    env_file:
      - ${ENV_FILE}
    networks:
      - network
    ports:
      - ${HOST_ADMIN_PORT}:${ADMIN_PORT}
      - ${HOST_BACKEND_PORT}:${BACKEND_PORT}

networks:
  network:
    driver: bridge

volumes:
  vvpi_db_data:
  redis_data:
