"""insert_places

Revision ID: 3607f5626ee8
Revises: 46a4be5361ae
Create Date: 2022-12-03 14:51:26.073185

"""
from alembic import op
import sqlalchemy as sa
from internal.entity.place import Place
import string


# revision identifiers, used by Alembic.
revision = '3607f5626ee8'
down_revision = '46a4be5361ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        Place.__table__,
        [
            {
                'name': name,
                'rent_cost': 100,
            }
            for name in [
                letter + digit 
                for letter in string.ascii_uppercase 
                for digit in string.digits
            ]
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
